### ISSUE TITLE
Cannot find module 'domain'.

### ISSUE THREAD

**Issue by freshfx** [odysseyscience/react-s3-uploader#24]
i have a problem with the react-s3-uploader s3router module.
i implement it this way (es6 compiled with babel)
```
import s3router from 'react-s3-uploader/s3router'
app.use('/s3', s3router({bucket:'bucket',region:'eu-central-1',ACL:'private'}))
```
if i try to run the compiled application i get this error
```
webpack:///./~/aws-sdk/lib_^\.\/.*$?:152
	return map[req] || (function() { throw new Error("Cannot find module '" + req
	                                       ^
Error: Cannot find module 'domain'.
    at eval (webpack:///./~/aws-sdk/lib_^\.\/.*$?:152:41)
    at webpackContextResolve (webpack:///./~/aws-sdk/lib_^\.\/.*$?:152:89)
    at webpackContext (webpack:///./~/aws-sdk/lib_^\.\/.*$?:149:29)
    at Object.nodeRequire (webpack:///./~/aws-sdk/lib/util.js?:40:55)
    at Object.eval (webpack:///./~/aws-sdk/lib/request.js?:4:23)
    at Object.<anonymous> (/Users/ffx-operator/RedBull/rbphotography/server/app-compiled.js:2195:2)
    at __webpack_require__ (/Users/ffx-operator/RedBull/rbphotography/server/app-compiled.js:20:30)
    at Object.eval (webpack:///./~/aws-sdk/lib/core.js?:86:1)
    at Object.<anonymous> (/Users/ffx-operator/RedBull/rbphotography/server/app-compiled.js:1919:2)
    at __webpack_require__ (/Users/ffx-operator/RedBull/rbphotography/server/app-compiled.js:20:30)
```

i use iojs-v1.6.3.
on iojs CLI i can require domain with `require('domain')` without any problems. Could it be a problem with webpack?

**Comment by seanadkinson** [comment]
Hmmm, we aren't requiring `domain` in this project, so it looks like it might be an issue more specific to `aws-sdk`.

I wonder if they are requiring `domsin

**Comment by freshfx** [comment]
This post solves my problem: http://jlongster.com/Backend-Apps-with-Webpack--Part-I

i have a module which exports the config for webpack in backend:
```
var path = require('path');
var fs = require('fs');

var nodeModules = {};
fs.readdirSync(path.join(__dirname, 'node_modules'))
  .filter(function(x) {
    // remove all react modules
    if (x.match(/^react/)) {
      return false
    }
    // remove the modules in this array from nodeModules
    return ['.bin'].indexOf(x) === -1;
  })
  .forEach(function(mod) {
    nodeModules[mod] = 'commonjs ' + mod;
  });

module.exports = {
  entry: './src/main.js',
  target: 'node',
  output: {
    path: path.join(__dirname, 'build'),
    filename: 'backend.js'
  },
  externals: nodeModules
}
```

**Comment by seanadkinson** [comment]
So this sounds like an issue with using webpack to bundle backend modules, and not with this project?  I'll close, but reopen if you think there is an issue.  Thanks.
