### ISSUE TITLE
Getting error with ES6

### ISSUE THREAD

**Issue by aamirafridi** [odysseyscience/react-s3-uploader#60]
My code

```js
import s3router from 'react-s3-uploader/s3router';
export default (app, auth) => {
  app.use('/s3', require('react-s3-uploader/s3router'))({
      bucket: 'jsan-assets',
      region: 'us-west-1', //optional
      // signatureVersion: 'v4', //optional (use for some amazon regions: frankfurt and others)
      // headers: {'Access-Control-Allow-Origin': '*'}, // optional
      // ACL: 'private' // this is default
    });
};

```

Where app is
`const app = express();`

```bash
/Users/aamirafridi/Sites/uroosi_web/node_modules/express/lib/router/index.js:130
  var search = 1 + req.url.indexOf('?');
                          ^

TypeError: Cannot read property 'indexOf' of undefined
    at Function.proto.handle (/Users/aamirafridi/Sites/uroosi_web/node_modules/express/lib/router/index.js:130:27)
    at EventEmitter.app.handle (/Users/aamirafridi/Sites/uroosi_web/node_modules/express/lib/application.js:170:10)
    at app (/Users/aamirafridi/Sites/uroosi_web/node_modules/express/lib/express.js:28:9)
    at exports.default.app.get (routes.js:16:3)
    at Object.<anonymous> (app.js:37:1)
    at Module._compile (module.js:413:34)
    at loader (/Users/aamirafridi/Sites/uroosi_web/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/aamirafridi/Sites/uroosi_web/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

```

**Comment by seanadkinson** [comment]
`req.url.indexOf('?');` is not a line from `s3router`, nor do I see any code from this library in the stacktrace.  Please re-open and clarify if you believe that this error is indeed caused by this code.  Thanks!

**Comment by aamirafridi** [comment]
basically express router fails on `require('react-s3-uploader/s3router')`
It works with all other routers

**Comment by seanadkinson** [comment]
Looks like you have a paren in the wrong spot.  Try this:

```
import s3router from 'react-s3-uploader/s3router';
export default (app, auth) => {
  app.use('/s3', require('react-s3-uploader/s3router')({
      bucket: 'jsan-assets',
      region: 'us-west-1', //optional
      // signatureVersion: 'v4', //optional (use for some amazon regions: frankfurt and others)
      // headers: {'Access-Control-Allow-Origin': '*'}, // optional
      // ACL: 'private' // this is default
    }));
};
```
